//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlobyAI.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlobyAI.Resources.Languages.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask from Bloby AI....
        /// </summary>
        internal static string AskFrromBlobyAI {
            get {
                return ResourceManager.GetString("AskFrromBlobyAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error: Connection to server Olاma could not be established!.
        /// </summary>
        internal static string Connection_error__Connection_to_server_Ollama_could_not_be_established_ {
            get {
                return ResourceManager.GetString("Connection error: Connection to server Ollama could not be established!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error: Received server response with code .
        /// </summary>
        internal static string Connection_error__Received_server_response_with_code {
            get {
                return ResourceManager.GetString("Connection error: Received server response with code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Settings.
        /// </summary>
        internal static string Connection_settings {
            get {
                return ResourceManager.GetString("Connection settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection successful!.
        /// </summary>
        internal static string Connection_successful_ {
            get {
                return ResourceManager.GetString("Connection successful!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to the server, HTTP status code:.
        /// </summary>
        internal static string Error_connecting_to_the_server__HTTP_status_code_ {
            get {
                return ResourceManager.GetString("Error connecting to the server, HTTP status code:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message:.
        /// </summary>
        internal static string Error_message_ {
            get {
                return ResourceManager.GetString("Error message:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Server.
        /// </summary>
        internal static string IP_Server {
            get {
                return ResourceManager.GetString("IP Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLM&apos;s list.
        /// </summary>
        internal static string LLMs_List {
            get {
                return ResourceManager.GetString("LLMs List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response received from the server!.
        /// </summary>
        internal static string No_response_received_from_the_server_ {
            get {
                return ResourceManager.GetString("No response received from the server!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to note: If the default port is utilized, no adjustments to the port setting are required..
        /// </summary>
        internal static string note_If_the_default_port_is_utilized__no_adjustments_to_the_port_setting_are_required_ {
            get {
                return ResourceManager.GetString("note If the default port is utilized, no adjustments to the port setting are requ" +
                        "ired.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian.
        /// </summary>
        internal static string Persian {
            get {
                return ResourceManager.GetString("Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please double-check the entered IP address and port..
        /// </summary>
        internal static string Please_double_check_the_entered_IP_address_and_port_ {
            get {
                return ResourceManager.GetString("Please double-check the entered IP address and port.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem processing server response!.
        /// </summary>
        internal static string Problem_processing_server_response_ {
            get {
                return ResourceManager.GetString("Problem processing server response!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your language.
        /// </summary>
        internal static string select_your_language {
            get {
                return ResourceManager.GetString("select your language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Checking connection status...
        /// </summary>
        internal static string Status__Checking_connection_status__ {
            get {
                return ResourceManager.GetString("Status: Checking connection status..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Connecting....
        /// </summary>
        internal static string Status__Connecting___ {
            get {
                return ResourceManager.GetString("Status: Connecting...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Message being processed by AI....
        /// </summary>
        internal static string Status__Message_being_processed_by_AI___ {
            get {
                return ResourceManager.GetString("Status: Message being processed by AI...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Processing and receiving the message....
        /// </summary>
        internal static string Status__Processing_and_receiving_the_message___ {
            get {
                return ResourceManager.GetString("Status: Processing and receiving the message...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Profile.
        /// </summary>
        internal static string Submit_Profile {
            get {
                return ResourceManager.GetString("Submit Profile", resourceCulture);
            }
        }
    }
}
